name: Execute SDK Standard Tests

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Node build repo'
        required: true
        default: 'release-1.5.5'
      run-java-tests:
        description: 'Run Java SDK Tests'
        required: true
        default: true
        type: boolean
      java-repo:
        description: 'Java Repo'
        required: false
        default: 'issues/e2e_integration'

jobs:

  build:

    runs-on: ubuntu-latest
    name: Execute SDK Tests

    steps:

      - name: Debug
        run: |
          ls -ltra


  workflow:

    if: ${{github.event.inputs.run-java-tests == 'true'}}
    needs: build
    name: Java SDK Tests
    uses: ./.github/workflows/sdk-java.yml
    with:
      java-repo: ${{ github.event.inputs.java-repo }}
      node-version: ${{ github.event.inputs.node-version }}
