name: Execute SDK Standard Tests

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Node build repo'
        required: true
        default: 'release-1.5.5'
      run-java-tests:
        description: 'Run Java SDK Tests'
        required: true
        default: true
        type: boolean
      java-repo:
        description: 'Java Repo'
        required: false
        default: 'issues/e2e_integration'
      run-python-tests:
        description: 'Run Python SDK Tests'
        required: true
        default: true
        type: boolean
      python-repo:
        description: 'Python Repo'
        required: false
        default: 'dev'

jobs:

  build:

    runs-on: ubuntu-latest
    name: Execute SDK Tests

    steps:

      - name: Debug
        run: |
          ls -ltra

      - name: Java SDK Tests
        if: ${{github.event.inputs.run-java-tests == 'true'}}
        uses: ./.github/workflows/sdk-java.yml
        with:
          java-repo: ${{ github.event.inputs.java-repo }}
          node-version: ${{ github.event.inputs.node-version }}

      - name: Python SDK Tests
        if: ${{github.event.inputs.run-python-tests == 'true'}}
        uses: ./.github/workflows/sdk-python.yml
        with:
          java-repo: ${{ github.event.inputs.java-repo }}
          node-version: ${{ github.event.inputs.node-version }}
